// Sidebar for the docs plugin. One top-level "Knowledge base" section, no
// "Start here" chrome. Each of the 5 areas (Policies, Patterns, Principles,
// Standards, Positions) uses Docusaurus autogenerated items, so any new
// file or sub-folder dropped into docs/<area>/ auto-appears in both the
// sidebar and the category index page (via the DocCategoryGeneratedIndexPage
// swizzle which groups by sub-folder).
//
// Zero manual updates needed when a new pattern gets PR'd into the KB.

import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "category",
      label: "Knowledge base",
      collapsed: false,
      link: {
        type: "generated-index",
        slug: "/knowledge-base",
        title: "Knowledge base",
        description:
          "Browse Entegris policies, patterns, principles, standards, and positions.",
      },
      items: [
        {
          type: "category",
          label: "Policies",
          collapsed: true,
          link: {
            type: "generated-index",
            slug: "/knowledge-base/policies",
            title: "Policies",
            description:
              "Mandatory rules that govern how Entegris builds, runs, and secures technology.",
          },
          items: [{ type: "autogenerated", dirName: "policies" }],
        },
        {
          type: "category",
          label: "Patterns",
          collapsed: true,
          link: {
            type: "generated-index",
            slug: "/knowledge-base/patterns",
            title: "Patterns",
            description:
              "Proven, reusable reference designs for common architecture problems across domains.",
          },
          items: [{ type: "autogenerated", dirName: "patterns" }],
        },
        {
          type: "category",
          label: "Principles",
          collapsed: true,
          link: {
            type: "generated-index",
            slug: "/knowledge-base/principles",
            title: "Principles",
            description:
              "The enduring beliefs and priorities that shape every architecture decision.",
          },
          items: [{ type: "autogenerated", dirName: "principles" }],
        },
        {
          type: "category",
          label: "Standards",
          collapsed: true,
          link: {
            type: "generated-index",
            slug: "/knowledge-base/standards",
            title: "Standards",
            description:
              "Specific, measurable requirements that implementations must meet to be compliant.",
          },
          items: [{ type: "autogenerated", dirName: "standards" }],
        },
        {
          type: "category",
          label: "Positions",
          collapsed: true,
          link: {
            type: "generated-index",
            slug: "/knowledge-base/positions",
            title: "Positions",
            description:
              "Recorded architecture positions on specific technologies, vendors, and approaches.",
          },
          // autogenerated - a "No positions yet" placeholder doc keeps the
          // category alive in the sidebar until real positions are added.
          // Delete the placeholder file once a real position ships.
          items: [{ type: "autogenerated", dirName: "positions" }],
        },
      ],
    },
  ],
};

export default sidebars;
