// AI4EA override of the classic theme's generated category index page.
//
// Default behaviour renders the category's children as a grid of cards. Per UX
// feedback we instead list every item (policies, patterns, principles,
// standards, positions) in an alternating grey/white table - the same look
// as the field/detail tables at the top of each doc - with each row linking
// straight into the item.
//
// When items span multiple sub-folders (patterns/analytics, patterns/data...)
// we group them by sub-folder and render each group as an expanded <details>
// section. Same page, one click to collapse a group you don't care about, no
// extra navigation into nested folders. New docs added to a sub-folder auto-
// appear under the right group next build.
//
// Row labels have the "Reference Architecture — " and "Integration Reference
// Architecture — " prefixes stripped since every pattern doc starts with one
// of those and it just adds noise to the list.
//
// Breadcrumbs, version banners, and the prev/next paginator are intentionally
// omitted here to match the site-wide "clean doc chrome" decision.

import { PageMetadata } from "@docusaurus/theme-common";
import {
  useCurrentSidebarCategory,
  useDocById,
} from "@docusaurus/plugin-content-docs/client";
import Heading from "@theme/Heading";
import Link from "@docusaurus/Link";
import type { Props } from "@theme/DocCategoryGeneratedIndexPage";
import type { ReactNode } from "react";

type SidebarItem = ReturnType<typeof useCurrentSidebarCategory>["items"][number];
type LinkItem = Extract<SidebarItem, { type: "link" }>;

// A row shown in the index table. Might come from a doc link, or from a
// top-level category that has its own landing page (e.g. the 5 KB areas).
type DisplayRow = {
  href: string;
  label: string;
  description?: string;
  docId?: string;
};

// Turn sidebar items into display rows. A category WITH its own landing page
// (like "Policies" → /knowledge-base/policies/) becomes one row that links to
// that page. A category WITHOUT its own page (autogenerated sub-folder like
// policies/cybersecurity/) is walked into and its children become rows.
function collectRows(items: readonly SidebarItem[]): DisplayRow[] {
  const out: DisplayRow[] = [];
  for (const item of items) {
    if (item.type === "link") {
      out.push({
        href: item.href,
        label: item.label,
        description: item.description,
        docId: item.docId,
      });
    } else if (item.type === "category") {
      if (item.href) {
        // has own landing page - show as a single row, don't walk in.
        // fall back to the KB area description map if the sidebar item
        // itself has no description (which is the usual case).
        out.push({
          href: item.href,
          label: item.label,
          description: item.description ?? KB_AREA_DESCRIPTIONS[item.label],
        });
      } else {
        out.push(...collectRows(item.items));
      }
    }
  }
  return out;
}

// One-line descriptions for the 5 top-level KB areas, shown on the KB main
// page. Mirrors the `link.description` values in sidebars.ts. Duplicated here
// because sidebar items don't surface the description through to the swizzle.
const KB_AREA_DESCRIPTIONS: Record<string, string> = {
  "Policies": "Mandatory rules that govern how Entegris builds, runs, and secures technology.",
  "Patterns": "Proven, reusable reference designs for common architecture problems across domains.",
  "Principles": "The enduring beliefs and priorities that shape every architecture decision.",
  "Standards": "Specific, measurable requirements that implementations must meet to be compliant.",
  "Positions": "Recorded architecture positions on specific technologies, vendors, and approaches.",
};

// Nice names for sub-folders. Unknown folders fall back to title-case of the
// slug (so a future patterns/security/ folder would show up as "Security"
// without any code change).
const SUBCATEGORY_LABELS: Record<string, string> = {
  "cybersecurity": "Cybersecurity",
  "operational": "Operational",
  "analytics": "Analytics",
  "application": "Application",
  "data": "Data",
  "infrastructure": "Infrastructure",
  "integration": "Integration",
  "application-systems": "Application & Systems",
  "missing": "Coming Soon (placeholders)",
};

function formatSubcategoryLabel(key: string): string {
  return (
    SUBCATEGORY_LABELS[key] ??
    key.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())
  );
}

// Pull the sub-folder from a doc id like "patterns/analytics/foo" -> "analytics".
// Returns null if the doc lives directly under the category (no sub-folder).
function getSubcategory(docId: string | undefined): string | null {
  if (!docId) return null;
  const parts = docId.split("/");
  return parts.length >= 3 ? parts[parts.length - 2] : null;
}

// Trim the noisy "Reference Architecture" prefix that every pattern doc uses
// as its H1. Keeps the actual doc title intact when opened.
function cleanLabel(label: string): string {
  return label.replace(
    /^(Integration Reference Architecture|Reference Architecture)\s*[—-]\s*/i,
    "",
  );
}

function IndexRow({
  href,
  label,
  description,
}: {
  href: string;
  label: string;
  description?: string;
}): ReactNode {
  return (
    <tr>
      <td>
        <Link to={href}>{cleanLabel(label)}</Link>
      </td>
      <td>{description ?? ""}</td>
    </tr>
  );
}

function DisplayRowTr({ row }: { row: DisplayRow }): ReactNode {
  // description falls back to the target doc's frontmatter description.
  const doc = useDocById(row.docId ?? undefined);
  return (
    <IndexRow
      href={row.href}
      label={row.label}
      description={row.description ?? doc?.description}
    />
  );
}

function IndexTable({ rows }: { rows: DisplayRow[] }): ReactNode {
  return (
    <table className="gc-index-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
        </tr>
      </thead>
      <tbody>
        {rows.map((row, index) => (
          <DisplayRowTr key={index} row={row} />
        ))}
      </tbody>
    </table>
  );
}

export default function DocCategoryGeneratedIndexPage({
  categoryGeneratedIndex,
}: Props): ReactNode {
  const category = useCurrentSidebarCategory();

  // Collect rows: sub-categories with their own landing page become single
  // rows (KB main page case); everything else gets walked into to produce
  // doc rows. Then group by sub-folder from each doc's id. Category rows
  // have no docId, so they land under the null bucket and render flat.
  const allRows = collectRows(category.items);
  const grouped = new Map<string | null, DisplayRow[]>();
  for (const row of allRows) {
    const sub = getSubcategory(row.docId);
    const bucket = grouped.get(sub) ?? [];
    bucket.push(row);
    grouped.set(sub, bucket);
  }

  // If everything is flat (single group with no sub-folder), skip the
  // <details> wrappers and just render one clean table - preserves the
  // current look for principles and positions.
  const isFlat = grouped.size === 1 && grouped.has(null);

  return (
    <>
      <PageMetadata
        title={categoryGeneratedIndex.title}
        description={categoryGeneratedIndex.description}
        keywords={categoryGeneratedIndex.keywords}
      />
      <div>
        <header>
          <Heading as="h1">{categoryGeneratedIndex.title}</Heading>
          {categoryGeneratedIndex.description && (
            <p>{categoryGeneratedIndex.description}</p>
          )}
        </header>
        <article className="margin-top--lg">
          {isFlat ? (
            <IndexTable rows={grouped.get(null) ?? []} />
          ) : (
            [...grouped.entries()].map(([sub, rows]) => (
              <details
                key={sub ?? "_flat"}
                open
                className="gc-index-group"
              >
                <summary className="gc-index-group__summary">
                  {sub === null ? "General" : formatSubcategoryLabel(sub)}
                  <span className="gc-index-group__count">
                    {rows.length}
                  </span>
                </summary>
                <IndexTable rows={rows} />
              </details>
            ))
          )}
        </article>
      </div>
    </>
  );
}
